### ISSUE TITLE
Download comments for premium videos.

### ISSUE THREAD

**Issue by Lywzc** [AlexAplin/nndownload#142]
Is it possible? I can access them on the website. The video itself won't play but comments are correctly retrieved as long as you are using Japanese IP.

This would be tremendously helpful if I missed the free time window for a video.

**Comment by AlexAplin** [comment]
Have you tried using `--skip-media`? I worked to support this exact use case previously: https://github.com/AlexAplin/nndownload/issues/102#issuecomment-927214324

**Comment by Lywzc** [comment]
Yes I tried.  The following error occured.
ParameterExtractionException: Failed to collect video paramters

**Comment by AlexAplin** [comment]
Please provide an example video and if possible please also provide the source of the page as an attachment when viewed in your browser (right click > View Page Source).

**Comment by Lywzc** [comment]
https://www.nicovideo.jp/watch/so43193316
[Source.txt](https://github.com/AlexAplin/nndownload/files/14039917/Source.txt)

**Comment by AlexAplin** [comment]
The only thing I can guess is that nndownload's traffic is not being correctly tunneled through your VPN, because that source from your browser shows the params data is there (`js-initial-watch-data`). The `Failed to collect video paramters` is only thrown when that is not present and it's not detected as region locked, but the region lock check probably needs to be updated because it doesn't look like what I see currently. 

I would recommend trying to capture the document request inside nndownload (e.g. add `print(document)` after L1018) so we can tell what it's actually seeing. My own VPN (Mullvad) doesn't seem to fool the region lock these days.

**Comment by Lywzc** [comment]
[Source.txt](https://github.com/AlexAplin/nndownload/files/14052629/Source.txt)
Here it is.

**Comment by AlexAplin** [comment]
>この動画は有料です。<br/>視聴するにはログインした後、動画を購入してください。

It's definitely not the same error, and the params is missing here. Are you using `-g`? If you're providing a login, is your account premium?

**Comment by Lywzc** [comment]
I thought I can access the comments without logging in. Seems that this is only true if the video is not premium. Premium videos require logging in to access the comments. No premium account is needed however.

I think this issue is solved.

**Comment by AlexAplin** [comment]
Yeah that appears to be the case, thanks!
