### ISSUE TITLE
Prevent mixing of video qualities on resuming downloads

### ISSUE THREAD

**Issue by Suika** [AlexAplin/nndownload#37]
Having downloaded files without the `--force-high-quality` during economy hours and then firing up the script with the flag `--force-high-quality` causes the file to be resumed: "Resuming previous download."

Resulting in "broken" file. The previous, low quality, video can still be played, but other data is lost.

Expected behaviour:
Upon detection of higher quality, the lower quality should be moved or replaced by the newer/better file.

**Comment by AlexAplin** [comment]
If you care about data loss, use `{qualtiy}` in the filename template to prevent improper file chaining. Since resuming only reads a simple byte position, it can't distinguish between a complete low quality video and an incomplete high quality video. Two possible long term solutions:

1.  Download to a temporary file with a quality suffix (e.g. `_low`) and then change the extension on completion. 
2. Use `{quality}` in the default filename format.

**Comment by AlexAplin** [comment]
If you care about data loss, use `{quality}` in the filename template to prevent improper file chaining. Since resuming only reads a simple byte position, it can't distinguish between a complete low quality video and an incomplete high quality video. Possible long term solutions:

1. Check if the file is complete by checking the integrity. Either a third party tool like ffprobe or maybe reading a chunk of previous bytes and comparing it to the download.
2. Use `{quality}` in the default filename format.

**Comment by Suika** [comment]
In case of high quality videos, `[{quality}][{video_quality}].{ext}` will result in `[auto][archive_h264_1080p].mp4`
In case of ?old content?: `[auto][__NONE__].mp4`

So I would guess that `{video_quality}` should be used?
As {quality} doesn't return anything viable.

**Comment by AlexAplin** [comment]
Only `quality` is available to all videos, where `auto` is high quality and `low` is low quality. The other qualities aren't reported on legacy videos. If `quality` is being misreported, that's something that needs to be looked into.

**Comment by AlexAplin** [comment]
Give 9159d4555944b91405d13196e573997109a52864 a try. This compares the tail bytes on the existing data and the download, only resuming if they match.

**Comment by Suika** [comment]
Tested it. As expected the download is not resumed in case of mismatching sizes.
At least there will be no files that are ~200mb big but play in 360p.

A bit more verbose information would be welcome, since it's hard to decide if the "different quality"/size is higher or lower in regards to the existing file. And having the video id in the same line would allow to programmatically decide if file should be kept or be replaced 

Optimal would be a flag that allows for file to be overwritten by a video of a bigger size.
Since bigger size + quality=auto would mean that the old file is of lower quality.
But that is up to you.

**Comment by AlexAplin** [comment]
I suspect people want the high quality if it's available by default, so the file will be overwritten when quality is `auto` if:
- The existing file length is less than the reported download length and the byte comparison window does not match **or**
- The existing file is negligibly small

When the quality is `low` and the byte window doesn't match, it'll report as such. I'll push this up in a few.

**Comment by Suika** [comment]
Thank you.
